#!/bin/bash

set -xe

[[ -d rootfs ]] && rm -rf rootfs

mkdir -p rootfs/{bin,sbin,etc,proc,sys,var,proc,lib/modules,usr/{bin,sbin}}
touch rootfs/proc/modules

cp -a busybox-1_36_0/_install/* rootfs/

cd rootfs

ln -sf bin/busybox init

mkdir -p etc/init.d
echo '#!/bin/sh' > etc/init.d/rcS
chmod +x etc/init.d/rcS

echo -e 'proc\t /proc\t proc\t defaults\t 0 1' > etc/fstab
echo 'mount -a' >> etc/init.d/rcS

mkdir dev
sudo mknod -m 660 dev/mem c 1 1
sudo mknod -m 660 dev/tty1 c 4 1
sudo mknod -m 660 dev/tty2 c 4 2
sudo mknod -m 660 dev/tty3 c 4 3
sudo mknod -m 660 dev/tty4 c 4 4

find . -print0 | cpio --null -o --format=newc | gzip -9 > ../rootfs.cpio.gz
